language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"

install: 
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt

script:
  - py.test --cov-report term --cov=pingdomexport pingdomexport

after_success:
  - pip install coveralls
  - coveralls
