language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"

install: 
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

script:
  - py.test

after_success:
  - pip install coveralls
  - coveralls
