- name: Create postgres db
  postgresql_db: name=pingdomexport
                 encoding='UTF-8'
                 lc_collate='de_DE.UTF-8'
                 lc_ctype='de_DE.UTF-8'
                 template='template0'
  become_user: postgres

- copy: src=schema.sql dest=/tmp

- name: Importing schema
  become_user: postgres
  shell: psql pingdomexport < /tmp/schema.sql

# psql -h localhost -U root pingdomexport
